### ISSUE TITLE
Missing support of regexp literal

### ISSUE THREAD

**Issue by veged** [alexwarth/ometa-js#1]
http://www.tinlizzie.org/ometa-js/#JavaScript_Compiler
`tree = JSParser.matchAll("var bla = /bla/", "topLevel")` -- failed to match

https://developer.mozilla.org/User:Potappo/Core_JavaScript_1.5_Reference/Global_Objects/RegExp_(constructor)

**Comment by alexwarth** [comment]
Closed, thanks to Sergey Kryzhanovsky.
