### ISSUE TITLE
commentary for http://www.tinlizzie.org/ometa-js needed

### ISSUE THREAD

**Issue by thulka** [alexwarth/ometa-js#21]
I read your research work "Experimenting with PL" / "ometa parsing.pdf" which was interesting and easy. I do not understand 

http://www.tinlizzie.org/ometa-js 

however. Whenever I press "do it" or "print it" after selecting "important info" and "go to project", I see errors in the changed source code.

**Comment by alexwarth** [comment]
Glad you enjoyed reading my dissertation.

About the user interface in OMeta/JS: you have to highlight the code that you want evaluate and then click either the "do it" or "print it" buttons, just like in a Smalltalk workspace.

If you're still having trouble, let's continue this discussion in the OMeta mailing list:
http://vpri.org/mailman/listinfo/ometa

Cheers,
Alex

**Comment by thulka** [comment]
thx alex,

this video also helped: https://www.youtube.com/watch?v=YEx4jfdFp1k

i think your work on ometa might reach even more audience from enhanced documentation.

**Comment by alexwarth** [comment]
I'm glad you got things working. And yes, better documentation would be great. Are you volunteering? ;)
