### ISSUE TITLE
Parsing issue

### ISSUE THREAD

**Issue by zanyoats** [alexwarth/ometa-js#23]
I am writing a parser for the smalltalk language and am having an problem with the following equivalent rules. One works (unaryExpr2) and the other (unaryExpr) parses short. Thanks!

```
ometa STParser { 
  tokRule = ...,
  primary = ...,
  unarySel = ...,
  ...
  // does not work
  unaryObjExpr  = unaryExpr | primary,
  unaryExpr = unaryObjExpr:mexpr tokRule('unarySel'):sel -> [`send, mexpr, sel],

  // works
  unaryExpr2 = (unaryExpr2 | primary):mexpr tokRule('unarySel'):sel -> [`send, mexpr, sel],
  ...
}
```

STParser.matchAll('56 double factorial', 'unaryExpr') = 
[send, [number, 56], [selector, double]]

STParser.matchAll('56 double factorial', 'unaryExpr2') = 
[send, [send, [number, 56], [selector, double]], [selector, factorial]]

**Comment by alexwarth** [comment]
Hi, Charlie The problem is that in the version that doesn't work, you have _indirect_ left recursion, which is not supported in OMeta/JS.

**Comment by zanyoats** [comment]
Hi,
I wasn't aware of that. Thanks for your timely response. Best!

On Thu, Aug 13, 2015 at 3:09 PM, Alessandro Warth notifications@github.com
wrote:

> Hi, Charlie The problem is that in the version that doesn't work, you have
> _indirect_ left recursion, which is not supported in OMeta/JS.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alexwarth/ometa-js/issues/23#issuecomment-130807187.

## 

~Charlie
