### ISSUE TITLE
Missed use cases of 'new' keyword

### ISSUE THREAD

**Issue by veged** [alexwarth/ometa-js#4]
`new` keyword can be used not only in form `"new" "name":n "(" listOf(#asgnExpr, ','):as ")"`. Other right use cases:

```
var n1 = new Bla,
    n2 = Bla.bla(),
    n2 = new ({a: {b: function() { console.log(arguments) }}}).a.b;
```

**Comment by alexwarth** [comment]
Please see my answer to issue #9:

https://github.com/alexwarth/ometa-js/issues/9

Cheers,
Alex
